Role.create(character_name: "RoleA")
Role.create(character_name: "RoleB")
Role.create(character_name: "RoleC")
Role.create(character_name: "RoleD")
Role.create(character_name: "RoleE")
Role.create(character_name: "RoleF")

Audition.create(actor: "ActorA", location: "LocationA", phone: 10, hired: false, role_id: 1)
Audition.create(actor: "Actora", location: "Locationa", phone: 11, hired: false, role_id: 1)
Audition.create(actor: "ActorB", location: "LocationB", phone: 12, hired: false, role_id: 2)
Audition.create(actor: "Actorb", location: "Locationb", phone: 13, hired: false, role_id: 2)
Audition.create(actor: "ActorC", location: "LocationC", phone: 14, hired: false, role_id: 3)
Audition.create(actor: "Actorc", location: "Locationc", phone: 15, hired: false, role_id: 3)
Audition.create(actor: "ActorD", location: "LocationD", phone: 16, hired: false, role_id: 4)
Audition.create(actor: "Actord", location: "Locationd", phone: 17, hired: false, role_id: 4)
Audition.create(actor: "ActorE", location: "LocationE", phone: 18, hired: false, role_id: 5)
Audition.create(actor: "Actore", location: "Locatione", phone: 19, hired: false, role_id: 5)